# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rw7szi6iZO0mziNchcr2KQc0I7X9VB3r
"""

from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import pandas as pd
from fastapi import HTTPException

from schemas import InputData
from validation import validate_dataframe

app = FastAPI()

# Load pipeline
bundle = joblib.load("pipeline.pkl")
model = bundle["model"]
scaler = bundle["scaler"]
features = bundle["features"]

@app.post("/predict")
def predict(data: InputData):

    df = pd.DataFrame([data.model_dump()])
    ok, result = validate_dataframe(df, features)

    if not ok:
        raise HTTPException(
            status_code=400,
            detail=result["error"]
        )

    df = result  # validated dataframe

    # preprocessing
    X = scaler.transform(df) # type: ignore

    # prediction
    proba = model.predict_proba(X)[0, 1] # type: ignore
    pred = int(proba > 0.5)
    
    return {
        "prediction": pred,
        "probability": float(proba)
    }